<<<<<<< HEAD
[project]
name = "data-dev-test"
version = "0.1.0"
description = "Entorno de desarrollo para el Diplomado en Estrategias de Datos."
package-mode = false
authors = [
    { name = "izainea", email = "cizaineam@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11,<4.0"

dependencies = [
    "jupyterlab>=4.2.3,<5.0.0",
    "sqlalchemy>=2.0.31,<3.0.0",
    "pyodbc>=5.1.0,<6.0.0",
    "pandas>=2.3.0,<3.0.0",
    "seaborn>=0.13.2,<0.14.0",
    "numpy>=2.3.0,<3.0.0",
    "scikit-learn>=1.7.0,<2.0.0",
    "torch==2.7.1"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
=======
[project]
name = "data-dev-test"
version = "0.1.0"
description = "Entorno de desarrollo para el Diplomado en Estrategias de Datos."
package-mode = false
authors = [
    { name = "izainea", email = "cizaineam@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.11,<4.0"

dependencies = [
    "jupyterlab>=4.2.3,<5.0.0",
    "sqlalchemy>=2.0.31,<3.0.0",
    "pyodbc>=5.1.0,<6.0.0",
    "pandas>=2.3.0,<3.0.0",
    "seaborn>=0.13.2,<0.14.0",
    "numpy>=2.3.0,<3.0.0",
    "scikit-learn>=1.7.0,<2.0.0",
    "torch==2.7.1"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
>>>>>>> fa19d75 (Fix docker)
